[package]
name = "zarigani"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13"
thiserror = "2.0"
anyhow = "1.0"
serde = { version="1.0", features = ["derive"] }
toml = "1.0.6"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# LLM Provider
rig-core = "0.32.0"

# # Discord
# serenity = "0.12"
# tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
